// This file is generated by Flutter tool.
// Do not manually edit this file.

import 'package:flutter_web_plugins/flutter_web_plugins.dart';

void registerPlugins(Registrar registrar) {
  // This function is empty because no plugins are being used in this project.
  // If plugins are added in the future, their registration code will be added here.
}
